[workspace]
resolver = "3"
members = []

[package]
name = "bevy-os"
version = "0.0.0"
publish = false
edition = "2024"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
version = "0.16.0-dev"
default-features = false
features = ["default_no_std"]

[dependencies]
aarch64-cpu = "10.0.0"
arm-gic = "0.2.2"
bitflags = "2.9.1"
buddy_system_allocator = "0.11.0"
chrono = { version = "0.4.41", default-features = false }
critical-section = { version = "1.2.0", features = ["restore-state-bool"] }
goblin = { version = "0.10.0", default-features = false, features = [
    "pe32",
    "pe64",
    "elf64",
    "elf32",
    "mach64",
    "mach32",
] }
log = "0.4.27"
once_cell = { version = "1.21.3", default-features = false, features = [
    "race",
] }
smccc = "0.2.1"
spin = "0.10.0"

[build-dependencies]
cc = { version = "1.2.27", features = ["parallel"] }
